language: go

go:
  - '1.14'

notifications:
  email: false

os: linux

jobs:
  include:
    - stage: style
      script: |
        diff <(goimports -d $(find . -type f -name '*.go' -not -path "*/vendor/*")) <(printf "")
        if [ $? -ne 0 ]; then
          echo "goimports format error" >&2
          exit 1
        fi
    - stage: anaylsis
      script: |
        go vet ./...
        if [ $? -ne 0 ]; then
          exit 1
        fi
    - stage: test
      script: |
        go test -race -cover ./pkg/...
<<<<<<< HEAD
        if [ $? -ne 0 ]; then
          exit 1
        fi
    - stage: e2e
      script: |
        ./test/test_runner.sh true
=======
>>>>>>> c752f79... fix: replace Datagram into Frame, fix switch core logic
        if [ $? -ne 0 ]; then
          exit 1
        fi
